rte-formated, v49

diff --git a/.github/workflows/docker-deploy.yml b/.github/workflows/docker-deploy.yml
--- a/.github/workflows/docker-deploy.yml
+++ b/.github/workflows/docker-deploy.yml
@@ -18,204 +18,194 @@ jobs:
         options: --privileged
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Set up .NET
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: '6.0.x'
+      - name: Set up .NET
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: '6.0.x'
 
-    - name: Set up Java 17
-      uses: actions/setup-java@v3
-      with:
-        distribution: 'temurin'
-        java-version: '17'    
+      - name: Set up Java 17
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '17'
 
-    - name: Clean up NuGet cache
-      run: dotnet nuget locals all --clear
+      - name: Clean up NuGet cache
+        run: dotnet nuget locals all --clear
 
-    - name: Restore dependencies for API Core
-      run: dotnet restore ./api/Basic3Tier.Core/Basic3Tier.Core.csproj
+      - name: Restore dependencies for API Core
+        run: dotnet restore ./api/Basic3Tier.Core/Basic3Tier.Core.csproj
 
-    - name: Restore dependencies for API Infrastructure
-      run: dotnet restore ./api/Basic3Tier.Infrastructure/Basic3Tier.Infrastructure.csproj
+      - name: Restore dependencies for API Infrastructure
+        run: dotnet restore ./api/Basic3Tier.Infrastructure/Basic3Tier.Infrastructure.csproj
 
-    - name: Restore dependencies for API Project
-      run: dotnet restore ./api/Basic3TierAPI/Basic3TierAPI.csproj
+      - name: Restore dependencies for API Project
+        run: dotnet restore ./api/Basic3TierAPI/Basic3TierAPI.csproj
 
-    - name: Build API Core
-      run: dotnet build --configuration Release --no-restore ./api/Basic3Tier.Core/Basic3Tier.Core.csproj
+      - name: Build API Core
+        run: dotnet build --configuration Release --no-restore ./api/Basic3Tier.Core/Basic3Tier.Core.csproj
 
-    - name: Build API Infrastructure
-      run: dotnet build --configuration Release --no-restore ./api/Basic3Tier.Infrastructure/Basic3Tier.Infrastructure.csproj
+      - name: Build API Infrastructure
+        run: dotnet build --configuration Release --no-restore ./api/Basic3Tier.Infrastructure/Basic3Tier.Infrastructure.csproj
 
-    - name: Build API Project
-      run: dotnet build --configuration Release --no-restore ./api/Basic3TierAPI/Basic3TierAPI.csproj
+      - name: Build API Project
+        run: dotnet build --configuration Release --no-restore ./api/Basic3TierAPI/Basic3TierAPI.csproj
 
-    - name: Run tests for API Core
-      run: dotnet test --no-build --verbosity normal ./api/Basic3Tier.Core/Basic3Tier.Core.csproj
+      - name: Run tests for API Core
+        run: dotnet test --no-build --verbosity normal ./api/Basic3Tier.Core/Basic3Tier.Core.csproj
 
-    - name: Run tests for API Infrastructure
-      run: dotnet test --no-build --verbosity normal ./api/Basic3Tier.Infrastructure/Basic3Tier.Infrastructure.csproj
+      - name: Run tests for API Infrastructure
+        run: dotnet test --no-build --verbosity normal ./api/Basic3Tier.Infrastructure/Basic3Tier.Infrastructure.csproj
 
-    - name: Run tests for API Project
-      run: dotnet test --no-build --verbosity normal ./api/Basic3TierAPI/Basic3TierAPI.csproj
+      - name: Run tests for API Project
+        run: dotnet test --no-build --verbosity normal ./api/Basic3TierAPI/Basic3TierAPI.csproj
 
+      - name: Set up SonarQube scanner
+        run: |
+          dotnet tool install --global dotnet-sonarscanner
+          export PATH="$PATH:/home/runner/.dotnet/tools"
 
-    - name: Set up SonarQube scanner
-      run: |
-        dotnet tool install --global dotnet-sonarscanner
-        export PATH="$PATH:/home/runner/.dotnet/tools"
-
-    - name: Run analysis
-      env:
+      - name: Run analysis
+        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
-      run: |
-        dotnet sonarscanner begin /k:"3-tier-cicd" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" 
-        dotnet build --no-incremental ./api/Basic3Tier.Core/Basic3Tier.Core.csproj
-        dotnet build --no-incremental ./api/Basic3Tier.Infrastructure/Basic3Tier.Infrastructure.csproj
-        dotnet build --no-incremental ./api/Basic3TierAPI/Basic3TierAPI.csproj
-        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
+        run: |
+          dotnet sonarscanner begin /k:"3-tier-cicd" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
+          dotnet build --no-incremental ./api/Basic3Tier.Core/Basic3Tier.Core.csproj
+          dotnet build --no-incremental ./api/Basic3Tier.Infrastructure/Basic3Tier.Infrastructure.csproj
+          dotnet build --no-incremental ./api/Basic3TierAPI/Basic3TierAPI.csproj
+          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
 
   dockerize:
     needs: build-test-scan
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Log in to DockerHub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Log in to DockerHub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Build Docker images
-      run: |
-        docker build -t gyaneshtiwari/3-tier-ui:latest ./ui
-        docker build -t gyaneshtiwari/3-tier-api:latest ./api
+      - name: Build Docker images
+        run: |
+          docker build -t gyaneshtiwari/3-tier-ui:latest ./ui
+          docker build -t gyaneshtiwari/3-tier-api:latest ./api
 
-    - name: Tag Docker images
-      run: |
-        docker tag gyaneshtiwari/3-tier-ui:latest gyaneshtiwari/3-tier-ui:1.0.0
-        docker tag gyaneshtiwari/3-tier-api:latest gyaneshtiwari/3-tier-api:1.0.0
+      - name: Tag Docker images
+        run: |
+          docker tag gyaneshtiwari/3-tier-ui:latest gyaneshtiwari/3-tier-ui:1.0.0
+          docker tag gyaneshtiwari/3-tier-api:latest gyaneshtiwari/3-tier-api:1.0.0
 
-    - name: Push Docker images
-      run: |
-        docker push gyaneshtiwari/3-tier-ui:latest
-        docker push gyaneshtiwari/3-tier-ui:1.0.0
-        docker push gyaneshtiwari/3-tier-api:latest
-        docker push gyaneshtiwari/3-tier-api:1.0.0
+      - name: Push Docker images
+        run: |
+          docker push gyaneshtiwari/3-tier-ui:latest
+          docker push gyaneshtiwari/3-tier-ui:1.0.0
+          docker push gyaneshtiwari/3-tier-api:latest
+          docker push gyaneshtiwari/3-tier-api:1.0.0
 
   deploy:
     needs: dockerize
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Setup SSH
-      uses: webfactory/ssh-agent@v0.5.3
-      with:
-        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+      - name: Setup SSH
+        uses: webfactory/ssh-agent@v0.5.3
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-    - name: Deploy to EC2
-      run: |
-        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=120 ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
-          if ! command -v screen &> /dev/null; then
-            echo "Screen is not installed. Installing screen..."
-            sudo apt-get update
-            sudo apt-get install -y screen
-          fi
-
-          screen -S deploy_session -d -m bash -c '
-            set -e
-       
-            #ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
-            # Ensure Docker and Docker Compose are installed
-            if ! command -v docker &> /dev/null; then
-              echo "Docker is not installed. Installing Docker..."
+      - name: Deploy to EC2
+        run: |
+          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=120 ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
+            if ! command -v screen &> /dev/null; then
+              echo "Screen is not installed. Installing screen..."
               sudo apt-get update
-              sudo apt-get install -y docker.io
+              sudo apt-get install -y screen
             fi
 
-            if ! command -v docker-compose &> /dev/null; then
-              echo "Docker Compose is not installed. Installing Docker Compose..."
-              sudo curl -L "https://github.com/docker/compose/releases/download/V2.16.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-              sudo chmod +x /usr/local/bin/docker-compose
-            fi  
+            screen -S deploy_session -d -m bash -c '
+              set -e
 
-            # Create the working directory
-            mkdir -p gyanesh
-            cd gyanesh
+              # Ensure Docker and Docker Compose are installed
+              if ! command -v docker &> /dev/null; then
+                echo "Docker is not installed. Installing Docker..."
+                sudo apt-get update
+                sudo apt-get install -y docker.io
+              fi
 
-            # Create docker-compose.yml
-            cat > docker-compose.yml <<EOL
-  version: "3.8"
-  services:
-    db:
-      image: postgres:latest
-      container_name: db_gyanesh
-      environment:
-        POSTGRES_USER: "postgres"
-        POSTGRES_PASSWORD: "admin123"
-        POSTGRES_DB: "basic3tier"
-      networks:
-        - network_gyanesh
+              if ! command -v docker-compose &> /dev/null; then
+                echo "Docker Compose is not installed. Installing Docker Compose..."
+                sudo curl -L "https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+                sudo chmod +x /usr/local/bin/docker-compose
+              fi  
 
-    api:
-      image: gyaneshtiwari/3-tier-api:latest
-      depends_on:
-        - db
-      environment:
-        - ConnectionStrings__Basic3Tier=Host=db;Port=5432;Database=basic3tier;Username=postgres;Password=admin123
-      ports:
-        - "7007:80"
-      networks:
-        - network_gyanesh
-      container_name: api_gyanesh
+              # Create the working directory
+              mkdir -p gyanesh
+              cd gyanesh
 
-    ui:
-      image: gyaneshtiwari/3-tier-ui:latest
-      depends_on:
-        - api
-      ports:
-        - "5005:80"
-      networks:
-        - network_gyanesh
-      container_name: ui_gyanesh
-  volumes:
-    db-data:
+              # Create docker-compose.yml
+              cat > docker-compose.yml <<EOL
+version: "3.8"
+services:
+  db:
+    image: postgres:latest
+    container_name: db_gyanesh
+    environment:
+      POSTGRES_USER: "postgres"
+      POSTGRES_PASSWORD: "admin123"
+      POSTGRES_DB: "basic3tier"
+    networks:
+      - network_gyanesh
 
-  networks:
-    network_gyanesh:
-      EOL
-    
-        #EOF
+  api:
+    image: gyaneshtiwari/3-tier-api:latest
+    depends_on:
+      - db
+    environment:
+      - ConnectionStrings__Basic3Tier=Host=db;Port=5432;Database=basic3tier;Username=postgres;Password=admin123
+    ports:
+      - "7007:80"
+    networks:
+      - network_gyanesh
+    container_name: api_gyanesh
 
-        #  Pull the latest images
-        #ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
-          echo "Pulling the latest images..."
-          cd gyanesh
-          docker-compose pull || { echo 'Docker pull failed' ; exit 1; }
-          echo "Pull completed."
-        
-        #EOF
- 
-        # Run Docker Compose
+  ui:
+    image: gyaneshtiwari/3-tier-ui:latest
+    depends_on:
+      - api
+    ports:
+      - "5005:80"
+    networks:
+      - network_gyanesh
+    container_name: ui_gyanesh
 
-        #ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
-          echo "Stopping existing containers..."
-          cd gyanesh
-          docker-compose down || { echo 'Docker down failed' ; exit 1; }
-          echo "Existing containers stopped."
+volumes:
+  db-data:
 
-          echo "Starting new containers..."
-          docker-compose up -d || { echo 'Docker up failed' ; exit 1; }
-          echo "Containers started."        
-        '
-      EOF
+networks:
+  network_gyanesh:
+              EOL
+
+              # Pull the latest images
+              echo "Pulling the latest images..."
+              docker-compose pull || { echo 'Docker pull failed' ; exit 1; }
+              echo "Pull completed."
+
+              # Run Docker Compose
+              echo "Stopping existing containers..."
+              docker-compose down || { echo 'Docker down failed' ; exit 1; }
+              echo "Existing containers stopped."
+
+              echo "Starting new containers..."
+              docker-compose up -d || { echo 'Docker up failed' ; exit 1; }
+              echo "Containers started."
+            '
+          EOF
